---
deployment:
  tasks:
    - export DEPLOYPATH=/home/discreto/public_html/
    - /bin/cp -R about $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R journal $DEPLOYPATH
    - /bin/cp -R pdfs $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp sitemap.txt $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH